version: '3'

services:
  api:
    build: .
    container_name: testing
    command: npm run dev
    ports:
      - '8000:8000'
    volumes:
      - .:/code
      - dependencies:/code/node_modules


volumes:
  dependencies:


